<doc.type html>
<script>
Html
Head
Utf8
ViewportContent=Width=Device-Width, Initial-Scale=ONE>
Title Covid Strings32 First Round Bracket
<Div Id=Bracket Class=Bracket></Div>
<Script Src=Bracket.JS>
Link Rel=Stylesheet Href=Css
Head
Body
Bracket-Container{}
Matchup
Solid Zero;
Padding 
Text Align Center 
Filename=Covid Strings32 First Round.JS
First Round=(Highest Overall Seed,Second Highest Seed, Third Highest Seed, First Middle Seed,Second Middle Seed, Third Lowest Seed,Second Lowest Seed,Lowest Overall Seed)
Highest Overall Seed =Seed1
Second Highest Seed=Seed2
Third Highest Seed=Seed3
Firstmiddleseed=Seed4
Second Middle Seed =Seed5
Third Lowest Seed= Seed6
Second Lowest Seed =Seed7
Lowest Overall Seed =Seed8
Covid Strings Team List32=[White,Black,Blue,Pink,Red,Burgundy,Purple,Orange]
Matchup1=(Red Versus Pink)
Matchup2=(Burgundy Versus Blue)
Matchup3=(Purple Versus Black)
Matchup4=(Orange Versus White)
Document.CreateElement 
matchup div.class name=(matchup)
matchupdiv.inner html=[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
Round Div=Create Element
round div class name=covid strings32 first round
bracket.appendchild(round div)
If (event.target.covid strings seed list.contains(matchup))
return matchup
else:
add matchup
java util.scanner
java.util
questions[]questions={
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
question15
if selectedanswer==correct:
return true
else:
return false
advancingteam=slice(current teams)
result=declarewinner(matchup1)
if pink  score>=forty:
console.log(pink covid disease fighters win)
else:
console.log(red protein spikers win)
result=declarewinner(matchup2)
if blue score>=forty:
console.log(blue curve crushers win)
else:
console.log(burgundy rebuilders Win)
result=declarewinne(matchup3)
if black score>=forty:
console.log(black night riders win)
else:
console.log(purple brave hearts win)
result=declarewinner(matchup4)
if white score>=forty:
console.log(white transit angels win)
else:
console.log(orange rna messengers win)
return filename
